#!/usr/bin/env bash

# Service-specific environment configuration
#
# THIS FILE IS GENERATED BY THE COMPOSER AND USED BY THE PIPELINE - MODIFICATION WILL BE OVERWRITTEN
#
# NOTE: This file should not be sourced directly. It is automatically sourced by env.sh
#       after validating the catalog-info.yaml and setting up Vault authentication.
#       Use: source env.sh [PATH] [--skip-vault] instead
#

# Check for --skip-vault flag
SKIP_VAULT=false
if [[ "${1:-}" == "--skip-vault" ]]; then
  SKIP_VAULT=true
fi

# Service-specific environment variables
export PROJECT_NAME="oscar-example"
export SERVICE_NAME="java-maven-pipeline-example"

# Maven build configuration
export POM_ROOT="./"
export MAVEN_ARGS="--file $POM_ROOT"

# Only fetch vault secrets if --skip-vault is not set
if [[ "$SKIP_VAULT" == false ]]; then
fi