---
- name: oneteam-example/java-maven-pipeline-example
  hosts: "{{ tomcat_server_hosts }}"
  collections:
    - polaris.deploy
  vars_files:
    - "vars/standard/all.yaml"
    - "vars/standard/{{env_vars}}.yaml"
    - "vars/custom/all.yaml"
    - "vars/custom/{{env_vars}}.yaml"

  roles:
    # Establish the port number
    - name: port_manager

    # prepare the installation environment by creating the necessary folders
    - name: create_project_directories

    # individual JDK installation
    - name: jdk
      vars:
        jdk_version:
          type: 'openjdk'
          major_version: 8
          url: '{{ artifactory_url }}/ext-binaries-local/openjdk/java-se-8u40-ri.tar.gz'
          filename: 'java-se-8u40-ri.tar.gz'
          checksum: 'sha1:606984531e3eeddba6be5ac626a229ef283c5de0'
          cacerts_path: 'jre/lib/security/cacerts'
        use_proxy: false

    # create a self signed certificate to allow for HTTPS
    - name: self_signed_cert

    # install & configure the Tomcat container
    - name: tomcat

    # deploy the webapp
    - name: webapp
      vars:
        webapp_war:
          context: "{{ context }}"
        webapp_root_log_level: "{{ log_level_root | default('INFO') }}"
        proxy_env: "{{ env_vars }}"
