---
- name: oneteam-example/java-maven-pipeline-example
  hosts: "{{ tomcat_server_hosts }}"
  collections:
    - polaris.deploy
  vars_files:
    - "vars/standard/all.yaml"
    - "vars/standard/{{env_vars}}.yaml"
    - "vars/custom/all.yaml"
    - "vars/custom/{{env_vars}}.yaml"

  roles:
    # Establish the port number
    - name: port_manager

    # prepare the installation environment by creating the necessary folders
    - name: create_project_directories

    # individual JDK installation
    - name: jdk
      vars:
        jdk_version:
          type: 'openjdk'
          major_version: 8
          url: 'https://api.adoptium.net/v3/assets/latest/8/hotspot?os=linux&architecture=x64'
          filename: 'OpenJDK8U-jdk_x64_linux_hotspot_8u422b05.tar.gz'
          checksum: 'sha256:4c6056f6167fae73ace7c3080b78940be5c87d54f5b08894b3517eed1cbb2c06'
          cacerts_path: 'jre/lib/security/cacerts'
        use_proxy: false

    # create a self signed certificate to allow for HTTPS
    - name: self_signed_cert

    # install & configure the Tomcat container
    - name: tomcat

    # deploy the webapp
    - name: webapp
      vars:
        webapp_war:
          context: "{{ context }}"
        webapp_root_log_level: "{{ log_level_root | default('INFO') }}"
        proxy_env: "{{ env_vars }}"
        skip_ojdbc_install: true
