name: Retain GHCR Package Versions

on:
  workflow_dispatch:

jobs:
  retain-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - package_name: java-maven-pipeline-example
            keep_versions: 10
          - package_name: deployment-config
            keep_versions: 10

    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ matrix.package_name }}
          package-type: container
          min-versions-to-keep: ${{ matrix.keep_versions }}
          ignore-versions: ${{ matrix.ignore_versions }}
          token: ${{ secrets.GITHUB_TOKEN }}