name: Run deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (development, test, production)'
        required: true
        type: choice
        options:
          - development
          - test
          - production
      config_branch:
        description: 'Use branch for testing configuration changes'
        required: false
        type: string

permissions:
  contents: read
  packages: read
  actions: read
  pull-requests: read

jobs:
  check-token-expiration:
    name: Check token expiration
    uses: ./.github/workflows/check-token.yaml
    secrets:
      token: ${{ secrets.broker_jwt_0e727e83_f027_426a_a31c_d7c1cceaddf6 }}

  deploy-dev:
    name: Deploy to development
    uses: ./.github/workflows/deploy.yaml
    needs: check-token-expiration
    with:
      environment: development
      config_branch: ${{ github.event.inputs.config_branch }}
    secrets: inherit
    if: |
      github.event.inputs.environment == 'development' ||
      github.event.inputs.environment == 'test' ||
      github.event.inputs.environment == 'production'

  deploy-test:
    name: Deploy to test
    uses: ./.github/workflows/deploy.yaml
    needs: deploy-dev
    with:
      environment: test
      config_branch: ${{ github.event.inputs.config_branch }}
    secrets: inherit
    if: |
      github.event.inputs.environment == 'test' ||
      github.event.inputs.environment == 'production'
 
  deploy-prod:
    name: Deploy to production
    uses: ./.github/workflows/deploy.yaml
    needs: deploy-test
    with:
      environment: production
      config_branch: ${{ github.event.inputs.config_branch }}
    secrets: inherit
    if: github.event.inputs.environment == 'production'
  